# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68cdd89034fcb4b9f9e1034e3b78f055eda5230956d56f258770886fd713c61a2d71afd307fe9334d5cb1d0ab7eec1d646a4d89ded6d9b8587156de28b7ac346

test:
  secret_key_base: 9512e096f0b56acaa837f8e12cecbdd0afa1cd50241bd2ad6e00a2dd2c6079fd130ae221132c324898f84b65e6d9457e000116c4979353192bcc2205b9fff4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
